### ISSUE TITLE
BUG: Config saving

### ISSUE THREAD

**Issue by skulblakka** [jonrainier/Live-Streamer-Plus#5]
It looks like the config isn't saved as it resets everytime I open the config tab.

**Comment by jonrainier** [comment]
I see the issue and it will be resolved in the next update. Thank you for reporting this issue!

**Comment by jonrainier** [comment]
Changes: https://github.com/Pwnoz0r/Live-Streamer-Plus/commit/ca1772ff1ff7f84c109d889f71c7eec65f395607

RC: https://github.com/Pwnoz0r/Live-Streamer-Plus/releases/tag/1.0.0.10
